[theme]
primaryColor = "#bf988a"
backgroundColor = "#031c26"
secondaryBackgroundColor = "#247c6d"
textColor = "#F0EEEB"
font = "sans serif"

[server]
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false